cursor #ff7ea1
cursor_text_color background

foreground #f1dee1
background #1a1113

selection_foreground #1a1113
selection_background #dd4578
url_color #ff88a8

# black / gray
color0  #150c0e
color8  #91737a

# red
color1  #ffc6bf
color9  #ff7d6e

# green / secondary
color2  #fbd0dc
color10 #f585a2

# yellow / tertiary
color3  #ffd1b8
color11 #ff955c

# blue / primary
color4  #ffd0dc
color12 #ff7ea1

# magenta / tertiary muted
color5  #ffc3a3
color13 #ff8e52

# cyan / secondary muted
color6  #fabdcd
color14 #f47294

# white
color7  #dbc0c5
color15 #f1dee1
